### ISSUE TITLE
Handle 1 Sslak and 1 Usslak in the same zone

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#206]
Almost done making all of the maps. Ran across this one tonight.

**Comment by ACG8** [comment]
I've been thinking about the best way to handle multiple objects. I've decided that the current format (placing them on grids) is not the best way. It would be better to assign each one a location individually.

For instance, we might write:
```
@Usslak=(1,1)
```
to place an Usslak in zone [1,1]. The same method could be used for markers. This allows us to place as many creatures/markers in a zone as we want.

This will, unfortunately, necessitate modifying the map code. Sorry.
Give me a little bit of time to figure out the format; there are still no spoilers for Domination, so the release is not imminent and we should have some time to finish the map code.

**Comment by sIKE23** [comment]
Yeah it is such a shame cause the Grid format is such an easy way to organize the data. The only other thing I came up with was to have multiple of the same section. So #Creatures# and if needed #Creatures2#.

**Comment by sIKE23** [comment]
The thought with my previous comment would be:
> @Objects = 1
> @Creatures = 1
 for most maps and if needed you could
> @Creatures = 2

Your processing statement would then use a for loop with a len statement populated with the @Creatures value.....

We would have to Change #Creatures# to #Creatures1# I would think if we were to go this route.....

**Comment by ACG8** [comment]
I would rather just eliminate ```#Creatures#``` altogether, and add objects individually.

For example, "Blasted Lands" would look like:
```
*...
45..
..28
...*
#Map#

@Orb=(0,1)
@Orb=(1,0)
@Orb=(1,2)
@Orb=(2,1)
@Orb=(2,3)
@Orb=(3,2)

@Sslak=(0,1)
@Sslak=(1,0)
@Sslak=(1,2)
@Sslak=(2,1)
@Sslak=(2,3)
@Sslak=(3,2)

@StartPosition1=(0,3)
@StartPosition2=(3,0)
```

Now that I think about it, this could be simplified somewhat with sets:

```
*...
45..
..28
...*
#Map#

@Orb=[(0,1),(1,0),(1,2),(2,1),(2,3),(3,2)]

@Sslak=[(0,1),(1,0),(1,2),(2,1),(2,3),(3,2)]

@StartPosition1=(0,3)
@StartPosition2=(3,0)
```

**Comment by sIKE23** [comment]
Would we change the Dictionary's from s to Sslak? And the same for the
other ones?

**Comment by sIKE23** [comment]
One suggestion, I know it is a python thing to start at 0 but it might be
smarter for us to use 1 thru 4 instead of 0 thru 3 and the script just has
a  - 1 (minus) to make the numbers python friendly.

You could also have two Dictionary's one for map pieces and one for
everything else...

**Comment by ACG8** [comment]
Yes, though the usage of the dictionaries would be a bit different. Rather than scanning through a grid and replacing each character with the corresponding dictionary entry, we would create a given object (such as a Sslak at the declared locations. Dictionaries are still the best way to handle this, though (honestly, most problems are best solved with dictionaries).

As for your suggestion, I was just wondering about that myself. It would certainly be more player-friendly, and is not any more difficult to code (just slightly uglier, but nobody except us is likely to see it anyway).

**Comment by sIKE23** [comment]
BTW Blasted Lands is an excellent example. As it has dupes...

@Scenario=[Domination,14]

*...
45..
..28
...*
#Map#

@Orb=[(1,2),(2,1),(2,3),(3,2),(3,4),(4,3)]

@Sslak=(1,2),(2,1),(2,3),(3,2),(3,4),(4,3)]

@SecretPassage=[(1,2),(4,3)]

@StartPosition1=(1,4)
@StartPosition2=(4,1)

The nice thing about this solution is you can handle Orbs and Secret
Passage as markers (the same size) from a layout and spacing POV.

**Comment by orb** [comment]
Could you be more careful with your `@mentions`? Thanks... :)

**Comment by sIKE23** [comment]
Opps sorry I thought that I made them a quote...still get caught with the
Markdown stuff sometimes.

**Comment by ACG8** [comment]
Ha ha ha...

**Comment by sIKE23** [comment]
Updated title to reflect all it encompasses  

@ACG8

**Comment by sIKE23** [comment]
The new solution is working like a champ! Closing out.
